Pearson-Higher-Ed/ux-test-platform

- pom.xml
- src/main/java/elements/elementsPageObjects/ResponsiveUtilitiesPageObjects.java
- src/main/java/elements/fixtures/responsive.html
- src/main/java/elements/utilities/CommonUtils.java
- src/test/java/elementsTests/BaseClass.java
- src/test/java/elementsTests/ResponsiveUtilitiesTest.java
- testng.xml
Add mobile tests for responsive utilities
> feat: Add mobile tests for responsive utilities

- src/main/java/elements/fixtures/icons.html
- src/test/java/elementsTests/IconsTest.java
- testng.xml
> feat: tests for new icons

- .travis.yml
feat: email notification on build failure
> feat: email notification on build failure

- .travis.yml
- pom.xml
- src/main/java/elements/fixtures/icons.html
- src/main/java/elements/utilities/CommonUtils.java
- src/main/resources/log4j.properties
- src/test/java/elementsTests/BaseClass.java
- src/test/java/elementsTests/IconsTest.java
- src/test/java/elementsTests/ResponsiveUtilitiesTest.java
- testng.xml
feat: handle asserts in a common method
> feat: handle asserts in a common method

- src/test/java/elementsTests/BaseClass.java
- src/test/java/elementsTests/IconsTest.java
- testng.xml
> style: renamed vm to sauce

- src/test/java/elementsTests/IconsTest.java
> perf: clean getCode method

- src/main/java/elements/elementsPageObjects/TypographyPageObjects.java
- src/main/java/elements/fixtures/typography.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/TypographyTest.java
- testng.xml
> Body Header List Code test

- src/main/java/elements/elementsPageObjects/TypographyPageObjects.java
- src/main/java/elements/fixtures/typography.html
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/IconsTest.java
- src/test/java/elementsTests/ResponsiveUtilitiesTest.java
- src/test/java/elementsTests/TypographyTest.java
- testng.xml
Written by eajaz
- Add typography tests.
- Add fixtures/typography.html elements
- Add pageobjects for typography.
> Des 187 typo tests

- src/main/java/elements/elementsPageObjects/ButtonsPageObjects.java
- src/main/java/elements/fixtures/buttons.html
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/main/shell_scripts/app-header.sh
- src/test/java/elementsTests/ButtonsTest.java
- testng.xml
Add buttons selenium tests for both mobile and desktop
> feat: fix focus test

- .travis.yml
- src/main/java/elements/fixtures/buttons.html
- src/main/java/elements/fixtures/icons.html
- src/main/java/elements/fixtures/responsive.html
- src/main/java/elements/fixtures/typography.html
- src/main/shell_scripts/elements.sh
Do git clone elements
npm install
point all html files to elements.css file
> feat: point to elements.css

- src/test/java/elementsTests/ResponsiveUtilitiesTest.java
- testng.xml
feat: minor changes to Responsive tests
> feat: minor changes to Responsive tests

- src/test/java/elementsTests/TypographyTest.java
- testng.xml
Skipping typography tests at the moment to have green master build. Some typography tests are failing, written by laxapana team. They will fix it and create a PR.
> feat: exclude typography test

- src/main/java/elements/elementsPageObjects/TypographyPageObjects.java
- src/test/java/elementsTests/TypographyTest.java
- testng.xml
Typography Mobile test are added.
> :Laxapana - Typography Pull Request

- src/main/java/elements/fixtures/typography.html
- src/test/java/elementsTests/ResponsiveUtilitiesTest.java
- src/test/java/elementsTests/TypographyTest.java
- testng.xml
Include Typography Tests back in the run
> Include Typography Tests back in the run

- src/main/java/elements/fixtures/icons.html
- src/test/java/elementsTests/IconsTest.java
- testng.xml
Add new icons to IconsTests.java
pe-icon--ban
pe-icon--camera
pe-icon--exclamation-circle
pe-icon--clock-o
> feat: Add new icons tests

- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/elementsTests/TypographyTest.java
- testng.xml
Added below files:
1. InputsPageObjects.java
2. inputs.html
3. InputsTest.java
Also updated 
1. BaseClass.java - added InputsPageObjects 
2. CommonUtils.java - hex2Rgba() and hex2Rgb() methods
> Pull Request : Input Text 

- src/test/java/elementsTests/TypographyTest.java
> feat: mac ff fixes

- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/elementsTests/TypographyTest.java
- testng.xml
Add checkbox and radio tests.
Incorporated the comments from @StommePoes
> feat: add checkbox and radio tests

- src/main/java/elements/fixtures/inputs.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/InputsTest.java
- testng.xml
feat: fix android tearDown() issue
> feat: fix android tearDown() issue

- .travis.yml
- pom.xml
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/InputsTest.java
- testng.xml
Add text area tests for both focus and non-focus styles.
> feat: Add text area tests

- .travis.yml
- SauceParam.properties
- elements_sdk.xml
- origami_v2.xml
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/main/java/utilities/SauceParam.java
- src/test/java/elementsTests/ButtonsTest.java
- src/test/java/elementsTests/CalendarTest.java
- src/test/java/elementsTests/IconsTest.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/elementsTests/ResponsiveUtilitiesTest.java
- src/test/java/elementsTests/TypographyTest.java
- src/test/java/origamiV2Tests/AppHeaderTest.java
- src/test/java/origamiV2Tests/ContextualHelpTest.java
Add support to trigger mobile test locally on sauce
Group test cases into various category such as desktop-ci, desktop-regression and mobile-regression
Fix some mobile test failures
> feat(group-test): Desktop Run - CI run

- origami_v2.xml
- pom.xml
- src/main/java/origamiV2/fixtures/componentArchetype/component-archetype.html
- src/main/java/origamiV2/jsfiles/componentArchetype/demo.js
- src/main/java/origamiV2/origamiV2PageObjects/ComponentArchetype.java
- src/main/java/utilities/BaseClass.java
- src/main/shell_scripts/origami-v2/app-header.sh
- src/main/shell_scripts/origami-v2/component-archetype.sh
- src/main/shell_scripts/origami-v2/contextual-help.sh
- src/main/shell_scripts/origami-v2/origami-v2.sh
- src/test/java/origamiV2Tests/ComponentArchetypeTest.java
Add tests for componentArchetype for both Desktop and Mobile.
> feat(component-archetype): Add tests for componentArchetype

- README.md
update readme for grouping tests.
> docs(group test):update readme for grouping tests

- README.md
Updated steps to trigger mobile tests locally
> docs(local-mobile-run): Updated steps to trigger mobile tests locally

- elements_sdk.xml
- src/main/java/elements/elementsPageObjects/ColorsPageObjects.java
- src/main/java/elements/fixtures/colors.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/ColorsTest.java
Add Colors Test for Desktop and Mobile
> feat(colors): Add Colors Test

- src/main/java/elements/elementsPageObjects/CalendarPageObjects.java
- src/main/java/elements/fixtures/Calendar.html
- src/test/java/elementsTests/CalendarTest.java
- src/test/java/elementsTests/TypographyTest.java
We have modified following files,
Calendar.html,
CalendarPageObjects.java,
CalendarTest.java
> Label-Change of Elements SDK Calendar

- .travis.yml
- origami_v2.xml
- pom.xml
- src/main/java/origamiV2/fixtures/drawer/drawer.html
- src/main/java/origamiV2/jsfiles/drawer/drawer.js
- src/main/java/origamiV2/origamiV2PageObjects/DrawerPageObjects.java
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/main/shell_scripts/origami-v2/drawer.sh
- src/main/shell_scripts/origami-v2/origami-v2.sh
- src/test/java/origamiV2Tests/AppHeaderTest.java
- src/test/java/origamiV2Tests/ComponentArchetypeTest.java
- src/test/java/origamiV2Tests/ContextualHelpTest.java
- src/test/java/origamiV2Tests/DrawerTest.java
Add tests for drawer component.
Desktop and mobile tests.
In BaseClass, moved all the page object class instantiation to a single method includePageObjects().
> feat(drawer): Add tests for drawer component

- elements_sdk.xml
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/TypographyTest.java
Additional Mobile Tests for Typography
> feat(Typography-mobiletest): Additional Mobile Tests for Typography

- src/main/java/utilities/BaseClass.java
- test_suites/elements_sdk.xml
> feat(parallelrun): Add Parallel support

- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/CalendarTest.java
Additional Tests for style changes
> feat(Calendar): Additional Tests for style changes

- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
Add tests for input group (des-210 - presentational search). Both desktop and mobile.
@StommePoes  @veerabvm for your review.
> feat(input-group): Add tests for input group

- src/main/java/elements/fixtures/icons.html
- src/test/java/elementsTests/IconsTest.java
> feat(icons): Add tests for new icons

- src/test/java/elementsTests/TypographyTest.java
> fix(typography):Fix tests for h5 and h6

- .travis.yml
- src/main/java/elements/elementsPageObjects/NoPlainCSSPageObjects.java
- src/main/java/elements/fixtures/icons.html
- src/main/java/elements/fixtures/noplain_css.html
- src/main/java/utilities/BaseClass.java
- src/main/shell_scripts/components.sh
- src/test/java/elementsTests/IconsTest.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/elementsTests/NoPlainCSSTest.java
Add tests(checkbox and radio) for NoPlainCSS.
@wyseguyonline for your review.
> feat(elementsNoPlainCSS): Add elements NoPlainCSS tests

- .travis.yml
- pom.xml
- src/main/java/elements/elementsPageObjects/MeterPageObjects.java
- src/main/java/elements/fixtures/meter.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/MeterTest.java
@StommePoes @antelopeb 
Include test for the &lt;progress&gt; element.
> feat(meter): Add meter tests

- .travis.yml
- src/main/java/elements/elementsPageObjects/GridPageObjects.java
- src/main/java/elements/fixtures/grid.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/GridTest.java
@JasonLantz @StommePoes @wyseguyonline @udhadpa for your review...
Add grid tests for both Desktop and Mobile.
Cover all the responsive breakpoints.
> feat(grid): Add grid tests

- src/main/java/origamiV2/fixtures/drawer/drawer.html
- src/main/java/origamiV2/origamiV2PageObjects/DrawerPageObjects.java
- src/main/java/utilities/CommonUtils.java
- src/test/java/origamiV2Tests/DrawerTest.java
Add a11y tests for open, close, tabbing order-focus styles.
@StommePoes @wyseguyonline @udhadpa @JasonLantz @mhomolak
> feat(drawer): Add a11y tests

- src/main/java/elements/elementsPageObjects/TemplatesPageObjects.java
- src/main/java/elements/fixtures/templates.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/TemplatesTest.java
Add tests for Templates : Desktop and Mobile.
@JasonLantz 
@umahaea 
@StommePoes 
@wyseguyonline
> feat(template): Add tests for templates

- .travis.yml
- src/main/java/elements/elementsPageObjects/PresentationStrategiesPageObjects.java
- src/main/java/elements/fixtures/presentation-strategies.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/PresentationStrategyTest.java
- src/test/java/elementsTests/TemplatesTest.java
- test_suites/elements_sdk.xml
Add desktop and mobile tests for presentation strategy
Cover default, centered, left/right strategy tests only.
> feat(P-strategy): Add tests for presentation strategy for DES-387 only

- .travis.yml
- src/main/java/origamiV2/fixtures/slider/slider.html
- src/main/java/origamiV2/jsfiles/slider/slider.js
- src/main/java/origamiV2/origamiV2PageObjects/SliderPageObjects.java
- src/main/java/utilities/BaseClass.java
- src/main/shell_scripts/components.sh
- src/test/java/origamiV2Tests/SliderTest.java
- test_suites/slider.xml
Hello All,
I have completed Desktop tests for Slider component. 
As you know we are facing issues with mobile automation, a separate ticket will be created to track the effort.
Please let me know your feedback.
Thanks,
@StommePoes 
@mhomolak 
@JasonLantz 
@wyseguyonline 
@umahaea
> Des 456 - Slider Component

- .travis.yml
- src/main/java/elements/elementsPageObjects/PresentationStrategiesPageObjects.java
- src/main/java/elements/fixtures/presentation-strategies.html
- src/test/java/elementsTests/PresentationStrategyTest.java
- test_suites/elements_sdk.xml
Hello All,
Please review my tests cases written for 
1. Default spacing
2. Small Gap spacing
3. Large Gap spacing. 
Let me know your feedback.
@JasonLantz @StommePoes @wyseguyonline @umahaea 
Thanks,
> feat(pr-strategy): Run tests for Spacing

- .travis.yml
- src/main/java/elements/elementsPageObjects/TypographyPageObjects.java
- src/main/java/elements/fixtures/typography.html
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/TypographyTest.java
- test_suites/elements_sdk.xml
* Fix tests for Typography for elements_sdk V1
* Optimize the code a bit by removing redundancies.
@StommePoes @wyseguyonline @JasonLantz @antelopeb @mhomolak
> feat(typography): Fix tests for Typography V1

- README.md
- src/main/java/elements/elementsPageObjects/ButtonsPageObjects.java
- src/main/java/elements/fixtures/buttons.html
- src/main/shell_scripts/components.sh
- src/test/java/elementsTests/ButtonsTest.java
- src/test/java/elementsTests/TypographyTest.java
- test_suites/elements_sdk.xml
* Fix tests for Buttons in elements sdk V1
* Add new test for xLarge button.
* Minor update in readme.
@StommePoes @JasonLantz @wyseguyonline @mhomolak for your review...
> feat(buttons): Fix buttons test for elements v1

- .travis.yml
- SauceParam.properties
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
* Fix tests for inputs for elements V1
> feat(inputs): Fix test for inputs in elements V1

- .travis.yml
- src/main/java/origamiV2/origamiV2PageObjects/ContextualHelpPageObjects.java
- src/main/shell_scripts/components.sh
- src/test/java/origamiV2Tests/ContextualHelpTest.java
* Update the page object variable for icons.
* Fix the tests.
@StommePoes @wyseguyonline @mhomolak @JasonLantz for your review.
> fix(contx-help): Fix tests for elements update

- .travis.yml
- SauceParam.properties
- src/main/java/elements/elementsPageObjects/ButtonsPageObjects.java
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/buttons.html
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/ButtonsTest.java
- src/test/java/elementsTests/InputsTest.java
* Add tests for checkboxes for elements V1. Both desktop and mobile
@JasonLantz @StommePoes @mhomolak @wyseguyonline @udhadpa for your review.
> feat(inputs): add checkbox tests

- .gitignore
- .travis.yml
- README.md
- package.json
- src/main/java/elements/elementsPageObjects/IconsPageObjects.java
- src/main/java/elements/fixtures/icons.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/IconsTest.java
- test_suites/elements_sdk.xml
* Add tests for icons
* Format the read me for good look-and-feel
* Add npm run elements-assets step to have svg file for local test runs.
* Assign the page objects class to null before instantiation.
@StommePoes @udhadpa @wyseguyonline @mhomolak for your review
> feat(icons): Add tests for icons

- .travis.yml
add C++ compilers add ons for node 6 issue
> add C++ compilers add ons for node 6 issue

- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/origamiV2/jsfiles/textModal/temp.js
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/origamiV2Tests/TextModalTest.java
- test_suites/elements_sdk.xml
Hi All,
This PR contains desktop and mobile tests for DES-481: Input password field.
Please let me know your feedback.
@StommePoes @JasonLantz @wyseguyonline @mcaskey 
Thank You
> feat(Inputs): Run tests for Inputs

- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
Hello All,
Please review my tests for Basic Input. It includes both desktop and mobile tests.
- Basic Input Single Line (Active & Focus)
- Basic Input Error (Active & Focus)
- Basic Input Disabled.
@JasonLantz @StommePoes @wyseguyonline @mhomolak @umahaea 
Thanks
> feat(inputs) : Add Basic Input tests

- src/main/java/elements/elementsPageObjects/FormsPageObjects.java
- src/main/java/elements/fixtures/forms.html
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsTests/FormsTest.java
- test_suites/elements_sdk.xml
Hello All,
Please review the tests written for form component.
It includes tests for css styling as per the redlines.
@JasonLantz @StommePoes @wyseguyonline @mhomolak @umahaea 
Thanks,
> feat(forms):Add tests for form component

- .gitignore
- .travis.yml
- pom.xml
- src/main/java/compounds/compoundsPageObjects/CompoundsButtonsPageObjects.java
- src/main/java/compounds/compoundsPageObjects/CompoundsIconsPageObjects.java
- src/main/java/compounds/fixtures/buttons.html
- src/main/java/compounds/fixtures/icons.html
- src/main/java/compounds/jsfiles/buttons/buttons.js
- src/main/java/compounds/jsfiles/buttons/temp.js
- src/main/java/compounds/jsfiles/icon/icons.js
- src/main/java/compounds/jsfiles/icon/temp.js
- src/main/java/elements/elementsPageObjects/IconsPageObjects.java
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/main/shell_scripts/components.sh
- src/test/java/compoundsTests/ButtonsTest.java
- src/test/java/compoundsTests/IconsTest.java
- test_suites/compounds_sdk.xml
- test_suites/elements_sdk.xml
Introduce compounds into ux-test-platform, so created necessary place holders.
Add tests for buttons and icons (both desktop and mobile)
Add some common methods for file operations
@StommePoes @JasonLantz @mhomolak @wyseguyonline @udhadpa for your review.
> feat(compounds): Add tests for buttons and icons

- test_suites/elements_sdk.xml
Hi All,
Please review the tests written for select input component. It covers the basic CSS styling as per the redlines given in the design doc.
I have added two tests 
1. Basic Select Input Test
2.Basic Select Input Test in Focus state
both for desktop and mobile.
@StommePoes @JasonLantz @wyseguyonline @mhomolak @umahaea 
Thanks,
> feat(input) : Add tests for Input Select

- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
Re-Added test for select input 
@umahaea
> feat(inputs): Add test for select input

- .travis.yml
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
Hello All,
Please review my tests for MultiLine Text input.
Tests written for basic and focus state css stylings for both desktop and mobile.
@mhomolak @StommePoes @JasonLantz @wyseguyonline @umahaea 
Thanks,
> feat(inputs): Add tests for MultiLine text input

- .travis.yml
- src/main/java/elements/elementsPageObjects/ButtonsPageObjects.java
- src/main/java/elements/fixtures/buttons.html
- src/test/java/elementsTests/ButtonsTest.java
Add tests for link buttons
Clean up a little bit of code, esp the focus operations not supported FF, safari selenium drivers.
@StommePoes @udhadpa @wyseguyonline @JasonLantz @mhomolak for your review.
> feat(link-buttons): Add tests for link buttons

- .travis.yml
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
Hi,
Please review my pull request for the IE-fix. It involves re-referencing of some css attributes  to appropriate elements.
- Also fixed the font-size issue for disabled input. 
@umahaea @mhomolak 
Thanks,
> (Inputs): Update tests to fix IE-issue inputs select

- .travis.yml
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
Hello All,
Please review my test written for radio buttons. 
I have written two tests one for desktop and mobile. This test method covers all the different states of radio button and their css styling.
Do let me know your comments/feedback.
@StommePoes @JasonLantz @wyseguyonline @mhomolak @umahaea 
Thanks,
> feat(inputs): Add tests for radio buttons

- src/test/java/origamiV2Tests/AppHeaderTest.java
- Fix absolute path issue for app-header Class. This will take care of setting absolute path for a file on any machine (local or travis). No more manually changing the paths :)
- Add one negative test for course mode(forgot to add in previous PR)
@udhadpa for your review.
> Fix absolute path issue for app-header

- .travis.yml
- src/main/java/origamiV2/fixtures/alerts/alerts.html
- src/main/java/origamiV2/jsfiles/alerts/alerts.js
- src/main/java/origamiV2/origamiV2PageObjects/AlertsPageObjects.java
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/main/shell_scripts/components.sh
- src/test/java/origamiV2Tests/AlertsTest.java
- test_suites/alerts.xml
Hello All, 
Please review my test for Alerts. 
It includes test cases as per the scenario sheet shared earlier.
Do let me know your feedback.
@mhomolak  @JasonLantz  @wyseguyonline  @umahaea 
Thanks,
> feat(alerts): Add tests for alerts

- .travis.yml
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
Add tests for pe-input--error_message
@JasonLantz @mhomolak @wyseguyonline @udhadpa for your review
> Add tests for input-error-message

- src/test/java/origamiV2Tests/AlertsTest.java
- src/test/java/origamiV2Tests/AppHeaderTest.java
- src/test/java/origamiV2Tests/AvatarDisplayTest.java
- src/test/java/origamiV2Tests/ContextualHelpTest.java
- src/test/java/origamiV2Tests/SliderTest.java
- src/test/java/origamiV2Tests/TextModalTest.java
Hi @umahaea : 
- added absolute paths to the origami components.
- re-referenced the read, write and Changeconfig methods to point to common utils.
Thanks
> Add absolute path origami components

- .travis.yml
- src/test/java/origamiV2Tests/ContextualHelpTest.java
- test_suites/contextual_help.xml
Fix tests for "New app-header slightly overlaps the drawer.".
@mhomolak @udhadpa @StommePoes @wyseguyonline @JasonLantz for your review.
> padding top fix for contextual-help-drawer

- .travis.yml
- src/main/java/elements/fixtures/buttons.html
- src/test/java/elementsTests/ButtonsTest.java
Fix tests for line-height of buttons.
@StommePoes @udhadpa @mhomolak @wyseguyonline @JasonLantz for your review.
> Test for line-height on fake buttons

- .travis.yml
- src/main/java/elements/elementsPageObjects/TypographyPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/elements/fixtures/typography.html
- src/main/java/utilities/CommonUtils.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/elementsTests/TypographyTest.java
- test_suites/elements_sdk.xml
Hello All,
Please review my tests for DES-606 (desktop +mobile)
- Added line-height test for lists. Test method "Verify pe-list"
Since all 'li' elements refer to class " .pe-list li " , I included only one test for line-height for this class
- Added test for aria-described by for Input error, test method "Verify Input Error Message Test"
this verifies the error message is the accessible description for this particular input. 
@StommePoes @umahaea @wyseguyonline @mhomolak 
Thanks
> Add test for line-height and aria described by

- .travis.yml
- src/main/java/origamiV2/fixtures/alerts/alerts.html
- src/main/java/origamiV2/origamiV2PageObjects/AlertsPageObjects.java
- src/test/java/origamiV2Tests/AlertsTest.java
Hello All,
Fixed test for capitalize alert types,
- changed alerts.html to reflect the change
- changed the id's in page objects file
@mhomolak @umahaea @wyseguyonline
> feat(alerts): fix test for capitalize

- src/test/java/elementsTests/ColorsTest.java
- src/test/java/elementsTests/FormsTest.java
- src/test/java/elementsTests/GridTest.java
- src/test/java/elementsTests/InputsTest.java
- src/test/java/elementsTests/MeterTest.java
- src/test/java/elementsTests/NoPlainCSSTest.java
- src/test/java/elementsTests/PresentationStrategyTest.java
- src/test/java/elementsTests/TemplatesTest.java
- src/test/java/elementsTests/TypographyTest.java
- src/test/java/origamiV2Tests/AvatarDisplayTest.java
- src/test/java/origamiV2Tests/DrawerTest.java
- src/test/java/origamiV2Tests/SliderTest.java
- src/test/java/origamiV2Tests/TextModalTest.java
Hi @umahaea 
This PR is for changing all boolean checks
eg : if (isFontColor == false)
to
if (!isFontColor)
to reduce down the verbiage as per Mike's suggestion
> fix test for boolean value check

- .travis.yml
- src/main/java/elements/elementsPageObjects/ButtonsPageObjects.java
- src/main/java/elements/fixtures/buttons.html
- src/test/java/elementsTests/ButtonsTest.java
- test_suites/elements_sdk.xml
Hello All,
Added test for link style button with padding, desktop & mobile.
Please review and let me know your comments.
Thanks,
> feat(buttons) : Add test for link style buttons

- .travis.yml
- src/test/java/elementsTests/ButtonsTest.java
Hello All,
This PR includes 
1. Fix test to remove underline as text-decoration for link-button 2.0 disabled
2. Added tests for link-button 2.0 for hover and focus states.
Please review and let me know. 
@mhomolak @JasonLantz @wyseguyonline @umahaea 
Thanks,
> feat(buttons): Fix tests for link buttons 2.0

- .travis.yml
- package.json
- src/main/java/origamiV2/origamiV2PageObjects/AppHeaderPageObjects.java
- src/test/java/origamiV2Tests/AppHeaderTest.java
Add test for tabble drop down -> forward and backward.
Fix the failing test.
> Add test for tabble drop down

- .travis.yml
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/elements/fixtures/inputs.html
- src/main/java/utilities/BaseClass.java
- src/main/java/utilities/CommonUtils.java
- src/main/resources/environment.properties
- src/test/java/elementsTests/InputsTest.java
- test_suites/elements_sdk.xml
Hello All,
This PR includes the changes to elements - Inputs. This is a combination PR (me and Eajaz's) 
1. Added tests for inputs -  all states (Active,Error, Disabled, Read Only)
2. Refactored old code to match the new design.
3. Refactored old lengthy tests into smaller ones for code maintainability.
Please review and let us know your comments.
@JasonLantz @wyseguyonline @StommePoes @mhomolak @umahaea 
Thanks,
> feat(inputs): Add tests for inputs for different states

- .travis.yml
- src/main/java/compounds/compoundsPageObjects/CompoundsLoadingIndicatorPageObjects.java
- src/main/java/compounds/fixtures/loadingIndicator.html
- src/main/java/compounds/jsfiles/loadingIndicator/loadingIndicator.js
- src/main/java/utilities/BaseClass.java
- src/test/java/compoundsTests/DropdownTest.java
- src/test/java/compoundsTests/LoadingIndicatorTest.java
Hello All,
Please review my tests for loading spinner. Note : These tests are only for spinner.
Jira story DES-669.
@wyseguyonline @StommePoes @JasonLantz @umahaea @mhomolak 
Thanks,
> feat(spinner):Add tests for loading spinner

- .travis.yml
- src/main/java/utilities/BaseClass.java
- src/test/java/compoundsTests/ButtonsTest.java
- test_suites/compounds_sdk.xml
Fix tests for compounds-buttons and turn it on "rebrand" branch.
> Fix tests for compounds buttons

- .travis.yml
- pom.xml
- src/main/java/compounds/compoundsPageObjects/CompoundsFooterPageObjects.java
- src/main/java/compounds/fixtures/buttons.html
- src/main/java/compounds/fixtures/footer.html
- src/main/java/compounds/fixtures/icons.html
- src/main/java/compounds/fixtures/modal.html
- src/main/java/compounds/jsfiles/footer/footer.js
- src/main/java/utilities/BaseClass.java
- src/main/resources/environment.properties
- src/test/java/compoundsTests/FooterTest.java
- test_suites/compounds_sdk.xml
- Add test for footer
- Pointed to latest dependencies in pom.xml
@mhomolak @StommePoes @JasonLantz @wyseguyonline @udhadpa for your review.
> feat(footer): Add tests

- .travis.yml
- package.json
- src/main/java/compounds/fixtures/buttons.html
- src/main/java/compounds/fixtures/dropdown.html
- src/main/java/compounds/fixtures/footer.html
- src/main/java/compounds/fixtures/icons.html
- src/main/java/compounds/fixtures/inputs.html
- src/main/java/compounds/fixtures/loadingIndicator.html
- src/main/shell_scripts/components.sh
- src/test/java/compoundsTests/DropdownTest.java
- test_suites/compounds_sdk.xml
- Point to eventInstantiator.compounds.js instead of dev
@JasonLantz @udhadpa for your review
> Point to eventInstantiator.compounds.js instead of dev

- .travis.yml
- src/main/java/origamiV2/origamiV2PageObjects/ContextualHelpPageObjects.java
- src/test/java/origamiV2Tests/ContextualHelpTest.java
Hello All,
Please review my tests for con-help. Updated some old tests.
As well as added new tests to cover the changes done by Mallory.
@StommePoes @JasonLantz @wyseguyonline @umahaea 
Thanks,
> feat(con-help): Update tests for con-help

- src/main/java/elements/elementsPageObjects/TemplatesPageObjects.java
- src/main/java/elements/fixtures/templates.html
- src/test/java/elementsTests/TemplatesTest.java
Hello All,
Please review my tests for 6/6 template and 10 column template. 
@JasonLantz @StommePoes @wyseguyonline @umahaea 
Thanks,
> feat(templates):Add test for 6/6 and 10 col template

- .travis.yml
- pom.xml
- src/main/java/compounds/compoundsPageObjects/CompoundsTabsPageObjects.java
- src/main/java/compounds/fixtures/tabs.html
- src/main/java/compounds/jsfiles/tabs/tabs.js
- src/main/java/utilities/BaseClass.java
- src/test/java/compoundsTests/TabsTest.java
- test_suites/compounds_sdk.xml
Add tests for Tabs
@mhomolak @StommePoes @udhadpa @wyseguyonline @JasonLantz for your review.
> feat(tabs): Add Tests

- .travis.yml
- src/main/java/elements/fixtures/inputs.html
- src/test/java/elementsTests/ButtonsTest.java
- src/test/java/elementsTests/InputsTest.java
@udhadpa for your review.
Fix tests for disabled class(inputs)
> Fix tests for disabled class(inputs)

- src/main/java/compounds/fixtures/dropdown.html
- src/main/java/compounds/jsfiles/dropdown/dropdown.js
- src/test/java/compoundsTests/DropdownTest.java
- test_suites/compounds_sdk.xml
Hi,
@umahaea for you review.
Added Favicon.ico file in the ux-test-platform to avoid the error seen in the browser logs.
Also changed the negative tests, the string passed as element id/component name now matches the dropdown.js file content
Thanks,
> feat(dropdown): Add favicon file and edit the negative tests

- .travis.yml
- src/main/java/origamiV2/fixtures/alerts/alerts.html
- src/main/java/origamiV2/origamiV2PageObjects/AlertsPageObjects.java
- src/test/java/origamiV2Tests/AlertsTest.java
Hello All,
Please review my PR for alerts DES-638
I have updated some old tests and added new tests as well.
@mhomolak @JasonLantz @umahaea @wyseguyonline 
Thanks,
> feat(alerts):Update and new Test for alerts

- .travis.yml
- src/main/java/utilities/BaseClass.java
> Set sauce job name

- .travis.yml
- pom.xml
- src/main/shell_scripts/components.sh
- test_suites/desktop_regression_suite.xml
- test_suites/mobile_regression_suite.xml
> Regression - speedup

- .travis.yml
- src/main/java/compounds/compoundsPageObjects/CompoundsBannerAlertsPageObjects.java
- src/main/java/compounds/fixtures/bannerAlerts.html
- src/main/java/compounds/jsfiles/bannerAlerts/bannerAlerts.js
- src/main/java/utilities/BaseClass.java
- src/test/java/compoundsTests/BannerAlertsTest.java
- test_suites/compounds_sdk.xml
Hello All,
Please review my tests for Banner alerts.Tests written for desktop + mobile.
@mhomolak @JasonLantz @wyseguyonline @umahaea @StommePoes 
Thanks,
> feat(banner-alerts):Add tests for banner alert

- .travis.yml
- src/main/java/compounds/compoundsPageObjects/CompoundsDropdownPageObjects.java
- src/main/java/compounds/jsfiles/dropdown/dropdown.js
- test_suites/compounds_sdk.xml
Fixed dropdown tests that failed during regression. 
Page Object values had to be changed.
@umahaea for you review
> fix dropdown failed tests

- .travis.yml
- src/test/java/origamiV2Tests/ModalTest.java
Add tests for focus forward and backward on modals with and without footer.
> Fix test for modal focus

- .travis.yml
- src/main/java/compounds/jsfiles/dropdown/dropdown.js
- src/test/java/compoundsTests/DropdownTest.java
Hi,
Update dropdown tests. Mike and Eajaz for your review.
@mhomolak @umahaea 
Thanks
> feat(dropdown): update dropdown tests

- .travis.yml
- src/main/java/compounds/jsfiles/inputs/inputs.js
- src/main/java/elements/elementsPageObjects/InputsPageObjects.java
- src/main/java/origamiV2/jsfiles/textModal/text-modal.js
- src/test/java/compoundsTests/InputsTest.java
Hi,
Updated Compounds->Inputs test as per the new changes.
Mainly updated the props list to contain additional props.
Mallory and Eajaz for your review
@StommePoes and @umahaea 
Thanks
> feat(comp-inputs):Update tests for inputs

- src/main/java/compounds/fixtures/dropdown.html
- src/main/java/compounds/jsfiles/dropdown/dropdown.js
- src/main/java/utilities/BaseClass.java
- src/test/java/compoundsTests/DropdownTest.java
Hi,
Please review my PR for the dropdown change.
Added new prop to the list and a new Test method - to check the callHandler function which prints the text of the selected option.
@umahaea for your review.
Thanks,
> feat(dropdown):Add test for CallHandler

- .travis.yml
- src/main/java/origamiV2/fixtures/loadingIndicator/loadingIndicator.html
- src/main/java/origamiV2/jsfiles/loadingIndicator/loadingIndicator.js
- src/main/java/origamiV2/origamiV2PageObjects/LoadingIndicatorPageObjects.java
- src/main/shell_scripts/components.sh
- src/test/java/origamiV2Tests/LoadingIndicatorTest.java
- test_suites/loadingIndicator.xml
Hello,
Please review my PR for loading indicator. Mobile and desktop tests covered.
@wyseguyonline @JasonLantz @StommePoes @mhomolak @umahaea 
Thanks,
> feat(load-ind): Add tests for loading indicator

- .travis.yml
- pom.xml
- src/test/java/compoundsTests/CalendarTest.java
- test_suites/compounds_sdk.xml
If last date of the month is the current date, had to verify the xpath for the cell next to it.
@udhadpa for your review..
> fix: calendar test for last date of month

- .travis.yml
- src/test/java/compoundsTests/ButtonsTest.java
- src/test/java/elementsTests/ButtonsTest.java
- test_suites/elements_sdk.xml
@mhomolak and @udhadpa for your review.
> Fix tests for primary buttons(background-color)

- .travis.yml
- src/main/java/compounds/compoundsPageObjects/CompoundsDropdownPageObjects.java
- src/main/java/compounds/compoundsPageObjects/CompoundsTablesPageObjects.java
- src/main/java/compounds/fixtures/tables.html
- src/main/java/compounds/jsfiles/tables/tables.js
- src/test/java/compoundsTests/InputsTest.java
- src/test/java/compoundsTests/TablesTest.java
Hello All,
Please review my tests for Tables. 
- Basic Table
- Sortable Table
- Selectable Table.
Note these tests cover functionality tests and no styling tests, these are have been covered under Elements.
@mhomolak @wyseguyonline @umahaea @StommePoes 
Thanks,
> feat(tables): Add tests for React Tables

- .travis.yml
- src/main/java/elements/elementsPageObjects/ButtonsPageObjects.java
- src/main/java/elements/fixtures/buttons.html
- src/main/java/elements/fixtures/tables.html
- src/test/java/elementsTests/ButtonsTest.java
@mhomolak @udhadpa for your review....
> Add tests for button groups

- src/main/shell_scripts/components.sh
- test_suites/compounds_sdk.xml
add temp compounds_sdk test suite until compounds repo is fully deprecated
> add temp compounds_sdk test suite

- README.md
- src/main/java/standAlone/standAlonePageObjects/ModalPageObjects.java
- src/test/java/standAloneTests/ModalTest.java
- test_suites/modal.xml
- add test for allow-ariahideapp-prop
> add test for allow-ariahideapp-prop

- .travis.yml
- src/main/java/standAlone/fixtures/pagination/pagination.html
- src/main/java/standAlone/jsfiles/pagination/pagination.js
- src/main/java/standAlone/standAlonePageObjects/PaginationPageObjects.java
- src/main/resources/environment.properties
- src/main/shell_scripts/components.sh
- src/test/java/standAloneTests/PaginationTest.java
Hello All,
Please review my PR for pagination (DES-544).
- Props in dispatch event are changed,so had to build a new config method
- Re-do old tests to match the new styles and functionality
- Added styling tests and new functionality tests to standard pagination
- Added tests for new type  - Compact Pagination.
Do let me know your feedback. 
@umahaea @briandunnpearson @wyseguyonline @mhomolak 
Thanks
> feat(pagination): Add tests for pagination

- .travis.yml
- src/main/java/elementsSDK/functional/fixtures/date-picker.html
- src/main/java/elementsSDK/functional/fixtures/time-picker.html
- src/main/java/elementsSDK/functional/functionalPageObjects/DatePickerPageObjects.java
- src/main/java/elementsSDK/functional/functionalPageObjects/TimePickerPageObjects.java
- src/main/java/elementsSDK/functional/jsfiles/datePicker/date-picker.js
- src/main/java/elementsSDK/functional/jsfiles/timePicker/time-picker.js
- src/main/java/utilities/CommonUtils.java
- src/main/java/utilities/RetryAnalyzer.java
- src/main/resources/environment.properties
- src/test/java/elementsSDKTests/functionalTests/DatePickerTest.java
- src/test/java/elementsSDKTests/functionalTests/InputsTest.java
- src/test/java/elementsSDKTests/functionalTests/TimePickerTest.java
- test_suites/compounds_sdk.xml
Add tests for date and time picker
Clean a little bit of common utils to handle exceptions in a better way
Add a retryanalyzer class to rerun failed tests to get it passed
> feat(date and time picker): Add tests

- .travis.yml
- src/main/java/standAlone/standAlonePageObjects/ModalPageObjects.java
- src/test/java/elementsSDKTests/functionalTests/DatePickerTest.java
- src/test/java/standAloneTests/ModalTest.java
- fix tests as per new design
- add a new test for modal margins
> fix(modal): tests as per new design

- .travis.yml
- src/main/java/elementsSDK/styles/fixtures/grid.html
- src/main/java/utilities/CommonUtils.java
- src/main/shell_scripts/components.sh
- src/test/java/standAloneTests/ModalTest.java
- test_suites/elements.xml
- test_suites/elements_sdk.xml
Introduce try-catch for all common methods.
Highlight the "exception" messages for clarity.
Provide room for elements only test suite run until it is fully deprecated on Dev side.
> Improvements in ux-test-platform

- src/main/java/elementsSDK/functional/fixtures/progress-bar.html
- src/main/java/elementsSDK/functional/functionalPageObjects/ProgressBarPageObjects.java
- src/main/java/elementsSDK/functional/jsfiles/progressBar/progress-bar.js
- src/main/java/utilities/BaseClass.java
- src/main/resources/environment.properties
- src/test/java/elementsSDKTests/functionalTests/CalendarTest.java
- src/test/java/elementsSDKTests/functionalTests/DatePickerTest.java
- src/test/java/elementsSDKTests/functionalTests/InputsTest.java
- src/test/java/elementsSDKTests/functionalTests/ProgressBarTest.java
- test_suites/elements_sdk.xml
> feat(progress-bar): Add tests

- .travis.yml
- src/main/java/standAlone/fixtures/coachMark/coach-mark.html
- src/main/java/standAlone/jsfiles/coachMark/coach-mark.js
- src/main/java/standAlone/standAlonePageObjects/CoachMarkPageObjects.java
- src/main/resources/environment.properties
- src/main/shell_scripts/components.sh
- src/test/java/standAloneTests/CoachMarkTest.java
- test_suites/coach_mark.xml
Hello All,
Please review my tests for coach mark.
@mhomolak @umahaea @wyseguyonline
> feat(coach-mark):Add tests

- .travis.yml
- src/main/java/standAlone/standAlonePageObjects/ModalPageObjects.java
Change the page objects xpath value to id's.
@umahaea
> Fix page objects xpath

- .travis.yml
- src/main/java/standAlone/standAlonePageObjects/AlertsPageObjects.java
- src/test/java/standAloneTests/AlertsTest.java
Update the padding and className for alerts Icon Test. 
@umahaea  for your review.
> Icon alerts

- .travis.yml
- src/main/java/elementsSDK/functional/functionalPageObjects/FunctionalDropdownPageObjects.java
- src/main/java/elementsSDK/functional/jsfiles/dropdown/dropdown.js
Hi,
Small change to Page Objects in dropdown class after the class name was changed in DES-840
@umahaea for your review,
Thanks
> fix dropdown test

- .travis.yml
- src/test/java/standAloneTests/ModalTest.java
Add test for modal scroll with page
> Add test for modal scroll with page

- .travis.yml
- src/main/java/standAlone/standAlonePageObjects/AppHeaderPageObjects.java
- src/test/java/standAloneTests/AppHeaderTest.java
Fix and add tests for below cases:
- aria expanded
- alt = User account menu
- dismiss dropdown in SHIFT+TAB
> Fix tests for a11y fixes

- package.json
- src/main/java/utilities/BaseClass.java
- src/test/java/elementsSDKTests/stylesTests/ButtonsTest.java
Hello,
Please review my PR for buttons test improvisation. Combined several tests into one for easy test maintainability.Reduced the number to 35. But it covers all the scenarios that were covered earlier.
2. Also added a small logic to auto start local webserver on your system when you run tests.No need to execute the command separately.Note : This works on Mac OS. 
@umahaea for your review.
Thanks,
> Update Buttons test and automate local wb launch locally

- .travis.yml
- src/main/java/elementsSDK/functional/jsfiles/inputs/inputs.js
- src/test/java/elementsSDKTests/functionalTests/InputsTest.java
Fix tests for radio and checkboxes as per the new config.
Clean buildJSONConfig() method.
> fix radio and checkbox tests

- .travis.yml
> chore: test a simple change

- .travis.yml
- src/test/java/standAloneTests/CoachMarkTest.java
Small PR to update test to reflect the new background color value. 
@umahaea @mhomolak
> feat(coach-mark):Update bgColor

- .travis.yml
- src/main/java/glp/functional/fixtures/glp-buttons.html
- src/main/java/glp/functional/functionalPageObjects/ButtonsPageObjects.java
- src/main/java/glp/functional/jsfiles/buttons/glp-buttons.js
- src/main/java/glp/styles/fixtures/glp-buttons.html
- src/main/java/glp/styles/stylesPageObjects/ButtonsPageObjects.java
- src/main/java/glp/styles/stylesPageObjects/FormsPageObjects.java
- src/test/java/glpTests/functionalTests/GLPButtonsTest.java
- src/test/java/glpTests/stylesTests/GLPButtonsTest.java
- src/test/java/glpTests/stylesTests/GLPFormsTest.java
- test_suites/glp_elements_sdk.xml
Hello All,
Please review my tests for Buttons v3.0.0. Styles plus functional test are written under tab - GLP
Do let me know your feedback.
Thanks,
Payal
> feat(button-v3):Add tests for buttons

- .travis.yml
- src/main/java/standAlone/fixtures/contextualHelp/app-header-BasicMode.html
- src/main/java/standAlone/fixtures/contextualHelp/app-header-CourseMode.html
- src/main/java/standAlone/fixtures/contextualHelp/app-header-IntegMode.html
- src/main/java/standAlone/fixtures/contextualHelp/app-header-SignOutMode.html
- src/main/java/standAlone/fixtures/contextualHelp/contextual-help.html
- src/main/java/standAlone/jsfiles/contextualHelp/contextual-help.js
- src/main/java/standAlone/standAlonePageObjects/ContextualHelpPageObjects.java
- src/test/java/standAloneTests/ContextualHelpTest.java
Hello,
Small PR to fix some content paths for help topic tests (mostly set in fixture files). Fixed some other tests as well.
Thank you
> Update paths for con-help

- .travis.yml
- src/main/java/elementsSDK/functional/jsfiles/dropdown/dropdown.js
- src/test/java/elementsSDKTests/functionalTests/InputsTest.java
- src/test/java/elementsSDKTests/stylesTests/InputsTest.java
Small PR for adding test for multiline inputs : border-radius.
> feat(inputs):Add test for multiline border radius

- .travis.yml
- src/test/java/standAloneTests/AlertsTest.java
Small PR to remove margin Top test. It is not in the design specs, was added from the dev end to make it look alike the designs.
> feat(alerts):Remove top margin test

- .travis.yml
- src/main/java/standAlone/standAlonePageObjects/AppHeaderPageObjects.java
Small PR to fix the paths as per new app-header changes
> feat(app-header):Fix path - alt
